import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import FacebookPixel from "@/components/FacebookPixel";
import { Toaster } from 'react-hot-toast';
import "./globals.css"
import { Suspense } from "react";

// Hind Siliguri font setup
const hindSiliguri = Hind_Siliguri({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["bengali", "latin"],
  display: "swap",
  variable: "--font-hind-siliguri",
});

export const metadata = {
  title: "Pixelwood",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">

      <body className={`${hindSiliguri.className} min-h-full flex flex-col`}  cz-shortcut-listen="true">
       <Suspense fallback={null}>
          <FacebookPixel />
        </Suspense>
        {children}
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}