import { Hind_Siliguri } from "next/font/google";
import "./globals.css";

// Hind Siliguri font setup
const hindSiliguri = Hind_Siliguri({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["bengali", "latin"],
  display: "swap",
  variable: "--font-hind-siliguri",
});

export const metadata = {
  title: "Pixelwood",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">

      <body className={`${hindSiliguri.className} min-h-full flex flex-col`}  cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}